### ISSUE TITLE
Mixin Cannot be consumed by an addon

### ISSUE THREAD

**Issue by runspired** [EmberSherpa/ember-velocity-mixin#2]
`velocityOptions` is always undefined for addons consuming this mixin.
- The docs should mention the `ember-cli-velocity` dependency and the need to configure `velocityOptions`.
- `velocityOptions` needs to be reworked to work in addons.

**Comment by runspired** [comment]
Looks like at least some issues (but doesn't look like this one) can be mitigated by updating the dependency version: https://github.com/taras/ember-cli-velocity/issues/2

**Comment by benkonrath** [comment]
I'm seeing this with ember-cli 1.13.1 and ember-velocity-mizin 0.2.2:

```
Cannot read property 'velocityOptions' of undefined
TypeError: Cannot read property 'velocityOptions' of undefined
```

Is this the correct install command?

```
npm install ember-velocity-mixin --save
```

Do you guys support the latest version of ember-cli with Ember 1.13?
